// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtHwpB55ZIEmMwCv-FZ28nzMWttXmw1II',
    appId: '1:558155467615:web:6fdb2532d559b005f904ea',
    messagingSenderId: '558155467615',
    projectId: 'chat-app-flutter101',
    authDomain: 'chat-app-flutter101.firebaseapp.com',
    storageBucket: 'chat-app-flutter101.appspot.com',
    measurementId: 'G-36VBSKZ3FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-CGNzfvUutRAoKcrXIwQ1bg_hPukLe30',
    appId: '1:558155467615:android:c94f9281196bb65bf904ea',
    messagingSenderId: '558155467615',
    projectId: 'chat-app-flutter101',
    storageBucket: 'chat-app-flutter101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYptG9WB7WMw5umnCtXC0WZSRITalDVsM',
    appId: '1:558155467615:ios:298d08e299188352f904ea',
    messagingSenderId: '558155467615',
    projectId: 'chat-app-flutter101',
    storageBucket: 'chat-app-flutter101.appspot.com',
    iosClientId: '558155467615-p7rafgt63g4bj33qt30324p5v4emfvl3.apps.googleusercontent.com',
    iosBundleId: 'com.sp.app.chat.chatApp',
  );
}
